from fastapi import FastAPI, Request, Query
from fastapi.responses import HTMLResponse, StreamingResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from src.services.gemini_service import GeminiService
from src.languages.factory import LanguageFactory
import json
import asyncio
import os

app = FastAPI()

# Setup Templates
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")

# Ensure templates dir exists
if not os.path.exists(TEMPLATES_DIR):
    os.makedirs(TEMPLATES_DIR)

templates = Jinja2Templates(directory=TEMPLATES_DIR)

# Initialize Service
gemini_service = GeminiService(model_name="gemini-3-flash-preview")

@app.get("/", response_class=HTMLResponse)
async def read_root(request: Request):
    return templates.TemplateResponse(request, "index.html")

from pydantic import BaseModel

class GenerateRequest(BaseModel):
    input_code: str
    language: str
    model: str
    use_reflection: bool = False

@app.post("/api/generate")
async def generate_code(req: GenerateRequest):
    # 1. Validation
    strategy = LanguageFactory.get_strategy(req.language)
    valid, msg = strategy.validate_code(req.input_code)
    
    if not valid:
        # Send an error fragment
        error_html = f'<div id="output-area" class="bg-red-900/20 border border-red-500 text-red-200 p-4 rounded-lg">{msg}</div>'
        return StreamingResponse(
            event_generator("datastar-merge-fragments", error_html),
            media_type="text/event-stream"
        )

    # 2. Setup System Instruction
    system_instruction = strategy.get_system_instruction()
    gemini_service.model_name = req.model

    async def generate_stream():
        full_response = ""
        ui_lang = strategy.get_syntax_name()
        
        # Initial Loading State
        yield format_sse("datastar-merge-fragments", 
             f'<div id="output-area" class="bg-gray-800 p-4 rounded-lg border border-gray-700 animate-pulse">Thinking...</div>')

        try:
            generator = gemini_service.generate_test_code(
                req.input_code, 
                system_instruction=system_instruction, 
                stream=True,
                use_reflection=req.use_reflection
            )
            
            if req.use_reflection:
                 yield format_sse("datastar-merge-fragments", 
                     f'<div id="output-area" class="bg-blue-900/20 border border-blue-500 text-blue-200 p-4 rounded-lg">Strict Syntax Nazi is reviewing your code... 🧐</div>')


            for chunk in generator:
                if chunk:
                    full_response += chunk
                    # Render Markdown/Code block
                    # We simply wrap it in a pre/code block and let the frontend (or just raw HTML) handle it.
                    # For simple streaming, we replace the whole block content.
                    html_content = f'''
                    <div id="output-area" class="w-full h-full bg-gray-900 rounded-lg border border-gray-700 overflow-hidden flex flex-col" data-on-load="@js('hljs.highlightElement(this.querySelector(\'code\'))')">
                        <div class="bg-gray-800 px-4 py-2 text-xs text-gray-400 font-mono border-b border-gray-700 flex justify-between">
                            <span>{ui_lang}</span>
                            <span>Generated by {req.model}</span>
                        </div>
                        <pre class="flex-1 p-4 overflow-auto font-mono text-sm text-gray-200 leading-relaxed custom-scrollbar"><code class="language-{ui_lang}">{full_response}</code></pre>
                    </div>
                    '''
                    yield format_sse("datastar-merge-fragments", html_content)
                    await asyncio.sleep(0.01) # Yield control
            
            # Final Success State (optional toast or class change)
            # We just leave the final code there.
            
        except Exception as e:
            error_html = f'<div id="output-area" class="bg-red-900/20 border border-red-500 text-red-200 p-4 rounded-lg">Error: {str(e)}</div>'
            yield format_sse("datastar-merge-fragments", error_html)

    return StreamingResponse(generate_stream(), media_type="text/event-stream")

def format_sse(event: str, data: str) -> str:
    """Formats an SSE message for Datastar."""
    lines = data.split('\n')
    formatted_data = "\n".join([f"data: {line}" for line in lines])
    return f"event: {event}\n{formatted_data}\n\n"

async def event_generator(event, data):
    yield format_sse(event, data)
